kind: pipeline
type: docker
name: "Build and Push ARM64"

platform:
  arch: arm64

trigger:
  event:
    - push
    - tag

steps:
  - name: fetch-tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: Build and Push (ARM64)
    image: plugins/docker
    pull: if-not-exists
    settings:
      auto_tag: true
      auto_tag_suffix: drone-arm64
      dockerfile: Dockerfile
      registry: docker.io
      repo:
        from_secret: dockerhub_repo
      username:
        from_secret: docker_username
      password:
        from_secret: dockerhub_token
      platform: linux/arm64
    when:
      event:
        - push
        - tag

---
## So they can run in parallel

kind: pipeline
type: docker
name: "Build and Push WindowsAMD64"

platform:
  os: windows
  arch: amd64

trigger:
  event:
    - push
    - tag

steps:
  - name: fetch-tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: Build and Push (WindowsAMD64)
    image: plugins/docker
    pull: if-not-exists
    settings:
      auto_tag: true
      auto_tag_suffix: drone-amd64
      dockerfile: Dockerfile
      registry: docker.io
      repo:
        from_secret: dockerhub_repo
      username:
        from_secret: docker_username
      password:
        from_secret: dockerhub_token
      platform: windows/amd64
    when:
      event:
        - push
        - tag
