kind: pipeline
type: docker
name: terragrunt-image

platform:
  arch: arm64

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git clone https://github.com/moabukar/terragrunt-image.git
      - git checkout ${DRONE_COMMIT}

  - name: build-and-publish
    image: gcr.io/kaniko-project/executor:latest
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: dockerhub_token
      REGISTRY: moabukar
    volumes:
      - name: docker-config
        path: /kaniko/.docker
    commands:
      - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_USERNAME\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - "/kaniko/executor --context=. --dockerfile=Dockerfile --destination=${REGISTRY}/terragrunt-image:${DRONE_COMMIT_SHA:0:7} --destination=${REGISTRY}/terragrunt-image:${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7} --destination=${REGISTRY}/terragrunt-image:latest"

volumes:
  - name: docker-config
    temp: {}

trigger:
  event:
    - push
  paths:
    include:
      - Dockerfile
      - requirements.txt
      - .drone.yml
