# kind: pipeline
# type: docker
# name: terragrunt-image

# platform:
#   arch: arm64

# steps:
#   - name: checkout
#     image: alpine/git
#     commands:
#       - git clone https://github.com/moabukar/terragrunt-image.git
#       - git checkout ${DRONE_COMMIT}

#   - name: build-and-publish
#     image: gcr.io/kaniko-project/executor:latest
#     environment:
#       DOCKER_USERNAME:
#         from_secret: docker_username
#       DOCKER_PASSWORD:
#         from_secret: dockerhub_token
#       REGISTRY: moabukar
#     volumes:
#       - name: docker-config
#         path: /kaniko/.docker
#     commands:
#       - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_USERNAME\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
#       - "/kaniko/executor --context=. --dockerfile=Dockerfile --destination=${REGISTRY}/terragrunt-image:${DRONE_COMMIT_SHA:0:7} --destination=${REGISTRY}/terragrunt-image:${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7} --destination=${REGISTRY}/terragrunt-image:latest"

# volumes:
#   - name: docker-config
#     temp: {}

# trigger:
#   event:
#     - push
#   paths:
#     include:
#       - Dockerfile
#       - requirements.txt
#       - .drone.yml

kind: pipeline
type: docker
name: "Build and Push Docker Images"

platform:
  arch: arm64

trigger:
  event:
    - push
    - tag

steps:
  - name: fetch-tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: Build and Push (ARM64)
    image: plugins/docker
    pull: if-not-exists
    settings:
      auto_tag: true
      auto_tag_suffix: linux-arm64
      dockerfile: Dockerfile
      registry: docker.io
      repo:
        from_secret: dockerhub_repo
      username:
        from_secret: docker_username
      password:
        from_secret: dockerhub_token
      platform: linux/arm64
    when:
      event:
        - push
        - tag

