kind: pipeline
type: docker
name: terragrunt-image

platform:
  arch: arm64

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git clone https://github.com/moabukar/terragrunt-image.git
      - git checkout ${DRONE_COMMIT}

  - name: build-and-publish
    image: docker:20.10.16-dind
    privileged: true
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: dockerhub_token
      REGISTRY: moabukar
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - sha=$(echo ${DRONE_COMMIT_SHA} | cut -c1-7)
      - primary_tag="${REGISTRY}/terragrunt-image:${sha}"
      # Start Docker daemon
      - dockerd-entrypoint.sh & sleep 5
      # Build and push image with commit SHA tag
      - docker build -t $primary_tag -f Dockerfile .
      - docker push $primary_tag
      # Tag and push based on branch
      - if [ "${DRONE_BRANCH}" = "main" ]; then
          retention_tag="${REGISTRY}/terragrunt-image:latest";
          docker tag $primary_tag $retention_tag;
          docker push $retention_tag;
        else
          retention_tag="${REGISTRY}/terragrunt-image:${DRONE_BRANCH}-${sha}";
          docker tag $primary_tag $retention_tag;
          docker push $retention_tag;
        fi

trigger:
  event:
    - push
  paths:
    include:
      - Dockerfile
      - requirements.txt
      - .drone.yml 
