kind: pipeline
type: docker
name: terragrunt-image

steps:
  - name: checkout
    image: alpine/git
    commands:
      - git clone https://github.com/moabukar/terragrunt-image.git
      - git checkout ${DRONE_COMMIT}

  - name: build-and-publish
    image: gcr.io/kaniko-project/executor:latest
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: dockerhub_token
      REGISTRY: moabukar
    commands:
      - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_USERNAME\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - sha=$(echo ${DRONE_COMMIT_SHA} | cut -c1-7)
      - primary_tag="${REGISTRY}/terragrunt-image:${sha}"
      # Build and push image with kaniko
      - /kaniko/executor --context . --dockerfile Dockerfile --destination $primary_tag
      # Tag and push based on branch
      - if [ "${DRONE_BRANCH}" = "main" ]; then
          retention_tag="${REGISTRY}/terragrunt-image:latest";
          /kaniko/executor --context . --dockerfile Dockerfile --destination $retention_tag;
        else
          retention_tag="${REGISTRY}/terragrunt-image:${DRONE_BRANCH}-${sha}";
          /kaniko/executor --context . --dockerfile Dockerfile --destination $retention_tag;
        fi

trigger:
  event:
    - push
  paths:
    include:
      - Dockerfile
      - requirements.txt
      - .drone.yml 
