name: terragrunt-image

on:
  push:
    paths:
      - .github/workflows/docker-build.yml
      - Dockerfile
      - requirements.txt

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Publish
      run: |
        registry="moabukar"
        sha=$(git rev-parse --short HEAD)
        primary_tag="${registry}/terragrunt-image:${sha}"

        # Build and push image with commit SHA tag
        docker build -t $primary_tag -f Dockerfile .
        docker push $primary_tag

        # Tag and push based on branch
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        if [ "$current_branch" = "main" ]; then
          retention_tag="${registry}/terragrunt-image:latest"
          docker tag $primary_tag $retention_tag
          docker push $retention_tag
        else
          retention_tag="${registry}/terragrunt-image:${current_branch}-${sha}"
          docker tag $primary_tag $retention_tag
          docker push $retention_tag
        fi
